apiVersion: 1

policies:
  - orgId: 1
    receiver: fa-alert-router
    group_by:
      - alertname
      - service
      - env
    routes:
      - receiver: fa-alert-router
        object_matchers:
          - ['app', '=', 'fishing-assistant']
