#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

FA_ENVIRONMENT="${FA_ENVIRONMENT:-}"
FA_GCP_PROJECT_ID="${FA_GCP_PROJECT_ID:-replace-with-gcp-project-id}"
FA_GRAFANA_INSTANCE_URL="${FA_GRAFANA_INSTANCE_URL:-https://example.grafana.net}"
FA_GRAFANA_LOKI_DATASOURCE_UID="${FA_GRAFANA_LOKI_DATASOURCE_UID:-grafanacloud-logs}"
FA_ALERT_ROUTER_WEBHOOK_URL="${FA_ALERT_ROUTER_WEBHOOK_URL:-https://fishing-assistant.online/alerts/grafana}"
FA_ALERT_ROUTER_GITHUB_REPOSITORY="${FA_ALERT_ROUTER_GITHUB_REPOSITORY:-pbuchman/fishing-assistant}"
FA_LOG_LEVEL="${FA_LOG_LEVEL:-info}"
FA_OBSERVABILITY_ENV_FILE="${FA_OBSERVABILITY_ENV_FILE:-/etc/fa/observability.env}"
FA_HETZNER_PROVISIONER_KEY_FILE="${FA_HETZNER_PROVISIONER_KEY_FILE:-/etc/fa/keys/provisioner-sa-key.json}"
deploy_user="deploy"
temp_env_file=""

FA_OBSERVABILITY_SECRETS=(
  FA_GRAFANA_LOKI_URL
  FA_GRAFANA_LOKI_USERNAME
  FA_GRAFANA_LOKI_TOKEN
  FA_ALERT_ROUTER_WEBHOOK_SECRET
  FA_ALERT_ROUTER_GITHUB_TOKEN
)

usage() {
  printf 'Usage: FA_ENVIRONMENT=prod %s [--output path]\n' "$(basename "$0")"
}

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

cleanup_temp_file() {
  [[ -n "${temp_env_file:-}" ]] && rm -f "${temp_env_file}"
}

require_prod() {
  [[ "${FA_ENVIRONMENT}" == "prod" ]] || fail "FA_ENVIRONMENT must be prod"
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --output)
        shift
        [[ $# -gt 0 ]] || fail "--output requires a value"
        FA_OBSERVABILITY_ENV_FILE="$1"
        shift
        ;;
      --output=*)
        FA_OBSERVABILITY_ENV_FILE="${1#*=}"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        fail "Unknown argument: $1"
        ;;
    esac
  done
}

dotenv_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  value="${value//$'\r'/\\r}"
  printf '"%s"' "${value}"
}

write_env_line() {
  local output_path="$1"
  local key="$2"
  local value="$3"
  printf '%s=%s\n' "${key}" "$(dotenv_escape "${value}")" >> "${output_path}"
}

write_static_env() {
  local output_path="$1"

  cat > "${output_path}" <<'HEADER'
# Generated by scripts/hetzner/load-observability-env.sh.
# Do not edit by hand. Secrets are sourced from GCP Secret Manager.
HEADER

  write_env_line "${output_path}" FA_ENVIRONMENT prod
  write_env_line "${output_path}" FA_GRAFANA_INSTANCE_URL "${FA_GRAFANA_INSTANCE_URL}"
  write_env_line "${output_path}" FA_GRAFANA_LOKI_DATASOURCE_UID "${FA_GRAFANA_LOKI_DATASOURCE_UID}"
  write_env_line "${output_path}" FA_ALERT_ROUTER_WEBHOOK_URL "${FA_ALERT_ROUTER_WEBHOOK_URL}"
  write_env_line "${output_path}" FA_ALERT_ROUTER_GITHUB_REPOSITORY "${FA_ALERT_ROUTER_GITHUB_REPOSITORY}"
  write_env_line "${output_path}" FA_LOG_LEVEL "${FA_LOG_LEVEL}"
}

validate_secret_name() {
  local secret_name="$1"
  [[ "${secret_name}" =~ ^FA_[A-Z0-9_]+$ ]] || fail "Invalid FA Secret Manager name: ${secret_name}"
}

read_secret() {
  local secret_name="$1"
  gcloud secrets versions access latest \
    --secret="${secret_name}" \
    --project="${FA_GCP_PROJECT_ID}"
}

append_secret() {
  local output_path="$1"
  local secret_name="$2"
  local secret_value=""

  validate_secret_name "${secret_name}"
  printf 'Loading secret %s\n' "${secret_name}" >&2
  secret_value="$(read_secret "${secret_name}")" || fail "Unable to read ${secret_name}"
  write_env_line "${output_path}" "${secret_name}" "${secret_value}"
}

main() {
  parse_args "$@"
  require_prod
  command -v gcloud >/dev/null 2>&1 || fail "gcloud CLI is required"
  id -u "${deploy_user}" >/dev/null 2>&1 || fail "Deploy user ${deploy_user} is required"

  [[ -r "${FA_HETZNER_PROVISIONER_KEY_FILE}" ]] ||
    fail "Provisioner service-account key is required: ${FA_HETZNER_PROVISIONER_KEY_FILE}"
  export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE="${FA_HETZNER_PROVISIONER_KEY_FILE}"

  umask 077
  temp_env_file="$(mktemp "${TMPDIR:-/tmp}/fa-observability-env.XXXXXX")"
  trap cleanup_temp_file EXIT

  write_static_env "${temp_env_file}"
  for secret_name in "${FA_OBSERVABILITY_SECRETS[@]}"; do
    append_secret "${temp_env_file}" "${secret_name}"
  done

  install -d -m 750 -o root -g "${deploy_user}" "$(dirname "${FA_OBSERVABILITY_ENV_FILE}")"
  install -m 640 -o root -g "${deploy_user}" "${temp_env_file}" "${FA_OBSERVABILITY_ENV_FILE}"
  printf 'Wrote %s with %s Secret Manager values\n' "${FA_OBSERVABILITY_ENV_FILE}" "${#FA_OBSERVABILITY_SECRETS[@]}"
}

main "$@"
